apiVersion: v1
kind: PersistentVolume
metadata:
    name: aurora-gov-database-pv
    namespace: aurora-gov
spec:
    storageClassName: aurora-gov-hostpath
    capacity:
        storage: 10Gi
    accessModes:
        -   ReadWriteMany
    hostPath:
        path: "/opt/aurora-gov-posgresql-volume"