apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: aurora-gov-database-pvc
    namespace: aurora-gov
spec:
    storageClassName: aurora-gov-hostpath
    accessModes:
        -   ReadWriteMany
    resources:
        requests:
            storage: 10Gi