apiVersion: v1
kind: Service
metadata:
    name: aurora-gov-database-service
    namespace: aurora-gov
spec:
    type: ClusterIP
    selector:
        app: aurora-gov-pgsql
    ports:
    -   protocol: TCP
        port: 5432
        targetPort: 5432